# -*- coding: utf-8 -*-
"""graficos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fW3Yd0pIOfop4DJNpKmnG-QefsfJjW2X
"""

import pandas as pd
import matplotlib.pyplot as plt

dados = pd.read_csv("output/conjuntos.csv")

colunas_necessarias = [
    "n_c", "avl_add", "rn_add", "b1_add", "b5_add", "b10_add",
    "avl_rem", "rn_rem", "b1_rem", "b5_rem", "b10_rem"]

dados = dados.sort_values("n_c")

# GRÁFICO 1 - Inserção
plt.figure(figsize=(12,6))

plt.plot(dados["n_c"], dados["avl_add"], label="AVL", linewidth=2)
plt.plot(dados["n_c"], dados["rn_add"], label="Rubro-Negra", linewidth=2)
plt.plot(dados["n_c"], dados["b1_add"], label="Árvore B (ordem 1)", linewidth=2)
plt.plot(dados["n_c"], dados["b5_add"], label="Árvore B (ordem 5)", linewidth=2)
plt.plot(dados["n_c"], dados["b10_add"], label="Árvore B (ordem 10)", linewidth=2)

plt.title("Esforço computacional da operação de insercao")
plt.xlabel("Tamanho do conjunto de dados")
plt.ylabel("Esforço computacional médio")

# plt.yscale("log")

plt.grid(True)
plt.legend()
plt.tight_layout()
plt.savefig("output/grafico_insercao.png", dpi=300)

# GRÁFICO 2 - Remoção
plt.figure(figsize=(12, 6))

plt.plot(dados["n_c"], dados["avl_rem"], label="AVL", linewidth=2)
plt.plot(dados["n_c"], dados["rn_rem"], label="Rubro-Negra", linewidth=2)
plt.plot(dados["n_c"], dados["b1_rem"], label="Árvore B (ordem 1)", linewidth=2)
plt.plot(dados["n_c"], dados["b5_rem"], label="Árvore B (ordem 5)", linewidth=2)
plt.plot(dados["n_c"], dados["b10_rem"], label="Árvore B (ordem 10)", linewidth=2)

plt.title("Esforço computacional da operação de remoção")
plt.xlabel("Tamanho do conjunto de dados")
plt.ylabel("Esforço computacional médio")

# plt.yscale("log")

plt.grid(True)
plt.legend()
plt.tight_layout()
plt.savefig("output/grafico_remocao.png", dpi=300)

print("Graficos exportados para \"output/\".")
